using System.Collections.ObjectModel;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

namespace Dragon.Copilot.Radiologists.Models;

/// <summary>
/// A single named section of a pre-draft report.
/// </summary>
/// <remarks>
/// Corresponds to the Section definition in pre-draft-report-schema.json.
/// </remarks>
public class Section
{
    /// <summary>
    /// Gets or sets the section name, in lower snake_case (for example <c>impression</c>).
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = null!;

    /// <summary>
    /// Gets or sets the section text, encoded per the parent structured report's format.
    /// </summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = null!;

    /// <summary>
    /// Gets or sets a value indicating whether this section was generated by AI.
    /// </summary>
    [JsonPropertyName("aiGenerated")]
    public bool AiGenerated { get; set; }

    /// <summary>
    /// Gets or sets the AI confidence for this section, between 0 and 1.
    /// </summary>
    [JsonPropertyName("aiConfidence")]
    public double AiConfidence { get; set; }

    /// <summary>
    /// Gets or sets the display order of this section within the report, starting at 1.
    /// </summary>
    [JsonPropertyName("sectionOrder")]
    public int SectionOrder { get; set; }

    /// <summary>
    /// Gets or sets the medical codes referenced in this section.
    /// </summary>
    [JsonPropertyName("codes")]
    [SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Needed for deserialization of partner payloads")]
    public Collection<Code>? Codes { get; set; }
}
